use `pcm`;

DROP EVENT IF EXISTS dropFreeUsers;

DELIMITER //

CREATE EVENT dropFreeUsers
ON SCHEDULE EVERY 1 DAY STARTS '2017-09-25 00:00:00'
ON COMPLETION PRESERVE ENABLE
DO
BEGIN
	SET SQL_SAFE_UPDATES = 0;
    DELETE FROM `users` WHERE (DATE(NOW()) > `expiration_date`);
END;


//

DELIMITER ;